### PR TITLE
Preparation Release v3.8.0

### PR DESCRIPTION
**Pull request by hadrienp-met**
## Goal

Update changelog for v3.8.0

## Type of change 

- [ ] Bugfix
- [ ] New feature
- [ ] Refactoring change
- [x] Release & Version Update (don't forget to change the version number in `package.mo`)

Will it break anything in previous models ?

- [ ] Breaking change (If yes, make sure to point it out in the changelog)
- [ ] Non-Breaking change

## Checklist

- [ ] I have added the appropriate tags, reviewers, projects (and detailed the size and priority of my PR) and linked issues to this PR
- [ ] I have performed a self-review of my own code
- [ ] I have checked that all existing tests pass.
- [ ] I have added/updated tests that prove my development works and does not break anything.
- [ ] I have made corresponding changes or additions to the documentation (in [Notion documentation](https://www.notion.so/metroscope/Metroscope-Modeling-Library-Documentation-MML3-WIP-50c8703c294446059d3b4a70d6ae4a71))
- [ ] I have added corresponding entries to the [Changelog](../CHANGELOG.md)
- [ ] I have checked for conflicts with target branch, and merged/rebased in consequence

You can also fill these out after creating the PR, but make sure to **check them all before submitting your PR for review**.

### CODE REVIEW

**Comment by nabily-met** [comment]
Correct if I'm mistaken, but there's no breaking changes in this version. So maybe we can 3.7.1 instead of 3.8.0.

**Comment by nabily-met** [comment]
Moreover, we should change the version in package.mo

**Comment by hadrienp-met** [comment]
I applied this rules :

> Given a version number MAJOR.MINOR.PATCH, increment the:
> - MAJOR version when you make incompatible API changes
> - MINOR version when you add functionality in a backward compatible manner
> - PATCH version when you make backward compatible bug fixes
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH forma

**Comment by hadrienp-met** [comment]
> Moreover, we should change the version in package.mo

Yes true

**Comment by nabily-met** [comment]
> I applied this rules :
> 
> > Given a version number MAJOR.MINOR.PATCH, increment the:
> > 
> > * MAJOR version when you make incompatible API changes
> > * MINOR version when you add functionality in a backward compatible manner
> > * PATCH version when you make backward compatible bug fixes
> >   Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH forma
> 
> For me here we have minor changes

Yes I agree ! So 3.8.0 🎉

**Review by nabily-met — APPROVED** [review]

**Pull request merged**
